mj:
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  accounts:
    - guild-id: 1168799994879422524
      channel-id: 1168799027245092905
      user-token: MTEONZE5NDk1MjM4MDU5Nj15NAGON9u6.D7GZNwqTMRenJpjp9007IPK4uVGYbF_rASA6w
      # user-agent: 
    - guild-id: 1177550062629421066
      channel-id: 1177548798084534292
      user-token: MTE3NZUONTExNTMONZE5Nzk3Mg.GWaWEc.5Wp32bi_qysMmmahqxwKMfSoQtbz_Xr_umG1W8
      # user-agent: xxxx